### ISSUE TITLE
AD7790.cpp typo

### ISSUE THREAD

**Issue by p-brane** [analogdevicesinc/arduino#1]
Line 32 of AD7790.cpp has a typo: 
 ui16AdcCodes = ((lomg)ui8AdcUpperCodes << 8) | ui8AdcLowerCodes;
should be
 ui16AdcCodes = ((long)ui8AdcUpperCodes << 8) | ui8AdcLowerCodes;

**Comment by bbushey** [comment]
Hi Jay,

Thanks for finding this and bringing it to my attention.  I will get this fixed and upload the fix in the next couple days.  

Thanks again,

Brandon
