### ISSUE TITLE
SD card stopped working with EVAL-CN0391-ARDZ shield

### ISSUE THREAD

**Issue by cryoguy** [analogdevicesinc/arduino#10]
I have a SD card built into a TFT LCD.  It works fine with both Uno and Mega 2560 board.   It stopped working when attached to this shield.  Any thought on why and any possible solutions?

**Comment by mirceacaprioru** [comment]
You should verify the current that your source can provide. There is the possibility that it won't suffice for the lcd and the shield. 

Are you using the USB ? If that is the case try to use a larger source with the barrel jack on the arduino.
