### ISSUE TITLE
Any example using i2c protocol?

### ISSUE THREAD

**Issue by BuzoXahn** [analogdevicesinc/arduino#11]
Hello, I bought the eval-adxl372z and I am using an ESP32 board for data capture, using the Arduino IDE, however now I want to use the I2C protocol, since I want to put multiple eval-adxl372z, my question is if I have to use other libraries or have an example. Thank you

**Comment by mirceacaprioru** [comment]
Hi

You will have to use the Wire library from Arduino.
https://www.arduino.cc/en/Reference.Wire

For adxl372 we don't have an i2c example only spi, but with the library it should not be so hard to tweak.
