### ISSUE TITLE
Arduino MEGA

### ISSUE THREAD

**Issue by shorty131** [analogdevicesinc/arduino#2]
Is not a issue,but question.

Does this work on arduino MEGA ?

Thanks.

**Comment by bbushey** [comment]
Hi Shorty,

I haven't tried this on the Arduino Mega, so I can't tell you with certainty.  But I would think if Arduino kept the same libraries, pin definitions, and functions for the Mega as they do the Uno, than the code and the board probably should work.

**Comment by shorty131** [comment]
Ok,i ordered today an  c0216 ,so in next 10 days i will try and tell you if it works,Thanks.
