### ISSUE TITLE
Any example applications for data logging or python plotting?

### ISSUE THREAD

**Issue by cryoguy** [analogdevicesinc/arduino#9]
I bought the EVAL-CN0391-ARDZ shield.  Are there any example applications for data logging to SD or live data plotting on TTF LCD or python plotting etc?  Thanks!

**Comment by mirceacaprioru** [comment]
Hi Cryoguy, 

We have this example with an LCD:
[https://github.com/analogdevicesinc/arduino/tree/master/Arduino%20Uno%20R3/examples/ADXL362_example]

Regards,
Mircea
